# Problem 12 from Project Euler

''' The sequence of triangle numbers is generated by adding the natural numbers. 

What is the value of the first triangle number to have over five hundred divisors? '''

def trianglenumber(number):
	return number * (number + 1) / 2